### ISSUE TITLE
ENH: Add materials for reproducing results in the paper

### ISSUE THREAD

**Issue by MountLee** [shamindras/bttv-aistats2020#3]
1. Python scripts of necessary utilities
2. IPython notebook of experiments & analysis
3. Data of NFL

**Comment by shamindras** [comment]
Thanks @MountLee! For `NFL` data, I'll prepare this in #1 and #2. Also we will put all `python` utilities in our [main bttv repo](https://github.com/shamindras/bttv/tree/master/bttv).

Once I finish #2 by tomorrow, I'll let you know, and you can add your awesome `ipython notebooks` in this repo.

**Comment by shamindras** [comment]
@MountLee - We have put in `NFL` data and `simulation` and `nfl_analysis` notebooks already in #9, so we can use this issue to add in `python` utilities per your reproducibility suggestion. I will do this shortly in a new PR related to this issue.

**Comment by shamindras** [comment]
Close this per #10
